/**
 * Список языков мира для переводчика меню UNIPUB.
 */
(function (global) {
  "use strict";

  var LANGUAGES = [
    { code: "ru", name: "Русский", native: true },
    { code: "kk", name: "Қазақша", native: true, mapTo: "kz" },
    { code: "en", name: "English", native: true },
    { code: "zh-CN", name: "中文 (简体)" },
    { code: "zh-TW", name: "中文 (繁體)" },
    { code: "ja", name: "日本語" },
    { code: "ko", name: "한국어" },
    { code: "ar", name: "العربية" },
    { code: "tr", name: "Türkçe" },
    { code: "de", name: "Deutsch" },
    { code: "fr", name: "Français" },
    { code: "es", name: "Español" },
    { code: "pt", name: "Português" },
    { code: "it", name: "Italiano" },
    { code: "pl", name: "Polski" },
    { code: "uk", name: "Українська" },
    { code: "uz", name: "Oʻzbekcha" },
    { code: "ky", name: "Кыргызча" },
    { code: "tg", name: "Тоҷикӣ" },
    { code: "az", name: "Azərbaycanca" },
    { code: "hy", name: "Հայերեն" },
    { code: "ka", name: "ქართული" },
    { code: "hi", name: "हिन्दी" },
    { code: "bn", name: "বাংলা" },
    { code: "ur", name: "اردو" },
    { code: "fa", name: "فارسی" },
    { code: "th", name: "ไทย" },
    { code: "vi", name: "Tiếng Việt" },
    { code: "id", name: "Bahasa Indonesia" },
    { code: "ms", name: "Bahasa Melayu" },
    { code: "tl", name: "Filipino" },
    { code: "nl", name: "Nederlands" },
    { code: "sv", name: "Svenska" },
    { code: "no", name: "Norsk" },
    { code: "da", name: "Dansk" },
    { code: "fi", name: "Suomi" },
    { code: "cs", name: "Čeština" },
    { code: "sk", name: "Slovenčina" },
    { code: "hu", name: "Magyar" },
    { code: "ro", name: "Română" },
    { code: "bg", name: "Български" },
    { code: "sr", name: "Српски" },
    { code: "hr", name: "Hrvatski" },
    { code: "el", name: "Ελληνικά" },
    { code: "he", name: "עברית" },
    { code: "sw", name: "Kiswahili" },
    { code: "am", name: "አማርኛ" },
    { code: "af", name: "Afrikaans" },
    { code: "sq", name: "Shqip" },
    { code: "eu", name: "Euskara" },
    { code: "ca", name: "Català" },
    { code: "gl", name: "Galego" },
    { code: "is", name: "Íslenska" },
    { code: "ga", name: "Gaeilge" },
    { code: "lt", name: "Lietuvių" },
    { code: "lv", name: "Latviešu" },
    { code: "et", name: "Eesti" },
    { code: "sl", name: "Slovenščina" },
    { code: "mk", name: "Македонски" },
    { code: "bs", name: "Bosanski" },
    { code: "mn", name: "Монгол" },
    { code: "ne", name: "नेपाली" },
    { code: "si", name: "සිංහල" },
    { code: "my", name: "မြန်မာ" },
    { code: "km", name: "ខ្មែរ" },
    { code: "lo", name: "ລາວ" },
    { code: "ta", name: "தமிழ்" },
    { code: "te", name: "తెలుగు" },
    { code: "ml", name: "മലയാളം" },
    { code: "kn", name: "ಕನ್ನಡ" },
    { code: "gu", name: "ગુજરાતી" },
    { code: "pa", name: "ਪੰਜਾਬੀ" },
    { code: "mr", name: "मराठी" },
    { code: "ha", name: "Hausa" },
    { code: "yo", name: "Yorùbá" },
    { code: "ig", name: "Igbo" },
    { code: "zu", name: "isiZulu" },
    { code: "xh", name: "isiXhosa" },
    { code: "so", name: "Soomaali" },
    { code: "rw", name: "Kinyarwanda" },
    { code: "mg", name: "Malagasy" },
    { code: "ny", name: "Chichewa" },
    { code: "sn", name: "ChiShona" },
    { code: "st", name: "Sesotho" },
    { code: "tn", name: "Setswana" },
    { code: "ts", name: "Xitsonga" },
    { code: "ss", name: "SiSwati" },
    { code: "ve", name: "Tshivenḓa" },
    { code: "eo", name: "Esperanto" },
    { code: "la", name: "Latina" },
    { code: "cy", name: "Cymraeg" },
    { code: "gd", name: "Gàidhlig" },
    { code: "mt", name: "Malti" },
    { code: "lb", name: "Lëtzebuergesch" },
    { code: "fy", name: "Frysk" },
    { code: "yi", name: "ייִדיש" },
    { code: "ku", name: "Kurdî" },
    { code: "ps", name: "پښتو" },
    { code: "sd", name: "سنڌي" },
    { code: "ckb", name: "کوردیی ناوەندی" },
    { code: "or", name: "ଓଡ଼ିଆ" },
    { code: "as", name: "অসমীয়া" },
    { code: "mai", name: "मैथिली" },
    { code: "ceb", name: "Cebuano" },
    { code: "jv", name: "Basa Jawa" },
    { code: "su", name: "Basa Sunda" },
    { code: "hmn", name: "Hmong" },
    { code: "haw", name: "ʻŌlelo Hawaiʻi" },
    { code: "sm", name: "Gagana Samoa" },
    { code: "mi", name: "Te Reo Māori" },
    { code: "be", name: "Беларуская" },
    { code: "tt", name: "Татар" },
    { code: "ba", name: "Башҡорт" },
    { code: "cv", name: "Чӑваш" },
    { code: "tk", name: "Türkmen" },
    { code: "ug", name: "ئۇيغۇرچە" },
    { code: "sa", name: "संस्कृतम्" },
    { code: "qu", name: "Runa Simi" },
    { code: "gn", name: "Avañeʼẽ" },
    { code: "ay", name: "Aymar" },
    { code: "dv", name: "ދިވެހި" },
    { code: "iu", name: "ᐃᓄᒃᑎᑐᑦ" },
    { code: "kl", name: "Kalaallisut" },
    { code: "se", name: "Davvisámegiella" },
    { code: "ht", name: "Kreyòl ayisyen" },
    { code: "co", name: "Corsu" },
    { code: "to", name: "lea fakatonga" },
    { code: "ty", name: "Reo Tahiti" },
    { code: "ak", name: "Akan" },
    { code: "bm", name: "Bamanankan" },
    { code: "ee", name: "Eʋegbe" },
    { code: "lg", name: "Luganda" },
    { code: "ln", name: "Lingála" },
    { code: "nyn", name: "Runyankore" },
    { code: "om", name: "Afaan Oromoo" },
    { code: "ti", name: "ትግርኛ" },
    { code: "kri", name: "Krio" },
    { code: "bho", name: "भोजपुरी" },
    { code: "doi", name: "डोगरी" },
    { code: "gom", name: "कोंकणी" },
    { code: "mni-Mtei", name: "ꯃꯤꯇꯩꯂꯣꯟ" },
    { code: "lus", name: "Mizo ṭawng" },
    { code: "sat", name: "ᱥᱟᱱᱛᱟᱲᱤ" },
    { code: "nso", name: "Sesotho sa Leboa" },
    { code: "ilo", name: "Ilokano" },
    { code: "war", name: "Winaray" },
    { code: "pt-PT", name: "Português (Portugal)" },
    { code: "pt-BR", name: "Português (Brasil)" }
  ];

  function find(code) {
    for (var i = 0; i < LANGUAGES.length; i += 1) {
      if (LANGUAGES[i].code === code || LANGUAGES[i].mapTo === code) return LANGUAGES[i];
    }
    return null;
  }

  function filter(query) {
    var q = String(query || "").toLowerCase().trim();
    if (!q) return LANGUAGES.slice();
    return LANGUAGES.filter(function (lang) {
      return (
        lang.name.toLowerCase().indexOf(q) !== -1 ||
        lang.code.toLowerCase().indexOf(q) !== -1 ||
        (lang.mapTo && lang.mapTo.toLowerCase().indexOf(q) !== -1)
      );
    });
  }

  global.UnipubLanguages = {
    list: LANGUAGES,
    find: find,
    filter: filter
  };
})(window);
